---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
  - parameters.yml
  sudo: yes
  roles:
  - { role: base }
  - { role: postgresql }
  tasks:
  - name: Install development tools
    apt: pkg={{ item }} state=latest
    sudo: yes
    with_items:
    - libxml2-utils
    - php-codesniffer
